### ISSUE TITLE
Maxima kernel fails to start in Jupyter Console, Notebook, and Lab

### ISSUE THREAD

**Issue by andresroliveira** [robert-dodier/maxima-jupyter#129]
When running the following command:

```
$ jupyter-console --kernel=maxima
```

the Maxima kernel fails to initialize. Similarly, attempts to use the Maxima kernel in Jupyter Notebook and Jupyter Lab result in the kernel being unresponsive and unable to execute any commands.

Below is the traceback when running the command in the console:

```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/jupyter_console/ptshell.py", line 434, in init_kernel_info
    reply = self.client.get_shell_msg(timeout=1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_client/client.py", line 143, in _async_get_shell_msg
    return await ensure_async(self.shell_channel.get_msg(*args, **kwargs))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_client/channels.py", line 232, in get_msg
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/jupyter-console", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_core/application.py", line 283, in launch_instance
    super().launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.12/site-packages/traitlets/config/application.py", line 1074, in launch_instance
    app.initialize(argv)
  File "/usr/lib/python3.12/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_console/app.py", line 136, in initialize
    self.init_shell()
  File "/usr/lib/python3.12/site-packages/jupyter_console/app.py", line 106, in init_shell
    self.shell = ZMQTerminalInteractiveShell.instance(parent=self,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/traitlets/config/configurable.py", line 583, in instance
    inst = cls(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/jupyter_console/ptshell.py", line 352, in __init__
    self.init_kernel_info()
  File "/usr/lib/python3.12/site-packages/jupyter_console/ptshell.py", line 437, in init_kernel_info
    raise RuntimeError("Kernel didn't respond to kernel_info_request") from e
RuntimeError: Kernel didn't respond to kernel_info_request
```

Software Versions:
SBCL: 2.4.9
CCL: 1.13
Maxima: 5.47.0
Jupyter Console: 6.6.3
Maxima-Jupyter: Installed via AUR

**Comment by yitzchak** [comment]
I made some changes in the common-lisp-jupyter kernel, so that could be the issue. I'll take a look.
