### ISSUE TITLE
aur pacman build maxima-jupyter-git on archlinux / 5.0.7-1-MANJARO

### ISSUE THREAD

**Issue by ng0177** [robert-dodier/maxima-jupyter#56]
pacman builds maxima-git w/o problems; however maxima-jupyter-git fails, see attached log - any ideas as to what might go wrong here? http://aur.archlinux.org/packages/maxima-jupyter-git Thanks!
[maxima-jupyter-arch.txt](https://github.com/robert-dodier/maxima-jupyter/files/3125432/maxima-jupyter-arch.txt)

**Comment by yitzchak** [comment]
It needs to be updated for some recent changes in Maxima-Jupyter. If I can fix #55 with a revamped install then I'll update the AUR package with that.

**Comment by ian-mitchell-001** [comment]
Just to give my own two cents on it, there's obviously the issue with the `$pkdir` on some parts. But, even after editing to fix that, there are errors building the package:

```
==> Building and installing package
==> Making package: maxima-jupyter-git r303.b3da307-1 (Fri 21 Jun 2019 09:29:54 AM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning maxima-jupyter-git git repo...
Cloning into bare repository '/tmp/yaourt-tmp-ian/aur-maxima-jupyter-git/maxima-jupyter-git'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1552 (delta 0), reused 1 (delta 0), pack-reused 1547
Receiving objects: 100% (1552/1552), 3.20 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (1054/1054), done.
==> Validating source files with sha256sums...
    maxima-jupyter-git ... Skipped
==> Extracting sources...
  -> Creating working copy of maxima-jupyter-git git repo...
Cloning into 'maxima-jupyter-git'...
done.
==> Starting pkgver()...
==> Updated version: maxima-jupyter-git r346.230515d-1
==> Entering fakeroot environment...
==> Starting package()...
install: cannot stat 'src/config.lisp': No such file or directory
==> ERROR: A failure occurred in package().
    Aborting...
==> ERROR: Makepkg was unable to build maxima-jupyter-git.
==> Restart building maxima-jupyter-git ? [y/N]
==> -------------------------------------------
==> 
```
All that needs to be be done is fix the file tree so that the files from `src` are installed. (But, more directories can be added if need be. )

There probably needs to be a change in the way the package compiles—though how to do that is beyond me.

After changing the `PKGBUILD` to look like this:

```sh
# Maintainer: Tarn Burton <twburton at gmail dot com>
pkgname=maxima-jupyter-git
pkgver=r346.230515d
pkgrel=1
pkgdesc="A Maxima kernel for Jupyter, based on CL-Jupyter (Common Lisp kernel)"
arch=("any")
url="https://github.com/robert-dodier/maxima-jupyter"
license=('BSD')
depends=("maxima")
source=(
  "$pkgname::git+https://github.com/robert-dodier/maxima-jupyter")
sha256sums=('SKIP')

pkgver() {
  cd $pkgname
  printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

package() {
  cd $pkgname
  # install -Dm644 load-maxima-jupyter.lisp "$pkgdir/usr/share/maxima-jupyter/load-maxima-jupyter.lisp"
  install -Dm644 src/additions.lisp "$pkgdir/usr/share/maxima-jupyter/src/additions.lisp"
  # install -Dm644 src/config.lisp "$pkgdir/usr/share/maxima-jupyter/src/config.lisp"
  # install -Dm644 src/evaluator.lisp "$pkgdir/usr/share/maxima-jupyter/src/evaluator.lisp"
  #install -Dm644 src/heartbeat.lisp "$pkgdir/usr/share/maxima-jupyter/src/heartbeat.lisp"
  #install -Dm644 src/iopub.lisp "$pkgdir/usr/share/maxima-jupyter/src/iopub.lisp"
  install -Dm644 src/kernel.lisp "$pkgdir/usr/share/maxima-jupyter/src/kernel.lisp"
  install -Dm644 src/maxima-jupyter.asd "$pkgdir/usr/share/maxima-jupyter/src/maxima-jupyter.asd"
  #install -Dm644 src/message.lisp "$pkgdir/usr/share/maxima-jupyter/src/message.lisp"
  install -Dm644 src/overrides-cl-info.lisp "$pkgdir/usr/share/maxima-jupyter/src/overrides-cl-info.lisp"
  install -Dm644 src/overrides.lisp "$pkgdir/usr/share/maxima-jupyter/src/overrides.lisp"
  install -Dm644 src/packages.lisp "$pkgdir/usr/share/maxima-jupyter/src/packages.lisp"
  install -Dm644 src/results.lisp "$pkgdir/usr/share/maxima-jupyter/src/results.lisp"
  #install -Dm644 src/shell.lisp "$pkgdir/usr/share/maxima-jupyter/src/shell.lisp"
  #install -Dm644 src/stdin.lisp "$pkgdir/usr/share/maxima-jupyter/src/stdin.lisp"
  #install -Dm644 src/utils.lisp "$pkgdir/usr/share/maxima-jupyter/src/utils.lisp"
  install -Dm644 -d "$pkgdir/usr/share/jupyter/kernels/maxima"
  python install-maxima-jupyter.py --root /usr/share/maxima-jupyter \
    --maxima /usr/bin/maxima --prefix "$pkgdir/usr"
  chmod 644 "$pkgdir/usr/share/jupyter/kernels/maxima/kernel.json"
  install -Dm644 LICENSE "$pkgdir/usr/share/licenses/$pkgname/LICENSE"
}
```

I could install the package just fine. However, running the package, I get

```python
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 73, in post
    type=mtype))
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/usr/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/lib/python3.7/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 160, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/usr/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/usr/lib/python3.7/site-packages/jupyter_client/manager.py", line 259, in start_kernel
    **kw)
  File "/usr/lib/python3.7/site-packages/jupyter_client/manager.py", line 204, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/usr/lib/python3.7/site-packages/jupyter_client/launcher.py", line 138, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'binary/maxima-5.43.0/maxima-local': 'binary/maxima-5.43.0/maxima-local'
```

To be honest, lisp programming is outside of the stuff I know. So yeah... I have no idea what is going on.

**Comment by robert-dodier** [comment]
I don't know anything about Archlinux, so, just looking at the log messages posted above, I see a couple of things. One is that the final message is `No such file or directory: 'binary/maxima-5.43.0/maxima-local': 'binary/maxima-5.43.0/maxima-local'`, which indicates that the attempt to build a Maxima executable (named `maxima-local`) has failed (and somebody, I'm not sure who, was trying to execute it). 

The other thing I see is that farther up it says `install: cannot stat 'src/config.lisp': No such file or directory` which means that `install` is looking for `src/config.lisp` which doesn't exist. Now `src/config.lisp` doesn't exist in the Maxima Git repo (neither does `src/config.lisp.in`, so I guess it's not auto-generated), so unless `src/config.lisp` is generated by some means, that can't work.

I don't know enough about the installation process to know what's going on with those two items. For what it's worth, according to the log messages which were posted, there wasn't a Lisp error. Hope this helps.
