### ISSUE TITLE
Jupyter Kernel Error (Installation using Old Method 2)

### ISSUE THREAD

**Issue by MarsSongco** [robert-dodier/maxima-jupyter#92]
I tried installing Maxima-Jupyter using old method 2 (Maxima-Jupyter loadable source installation) and I got this message indicating that I have installed maxima-jupyter successfully.

![maxima-jupyter installed](https://user-images.githubusercontent.com/63143891/108168455-4d0e0500-7132-11eb-9920-7a846ad9dd00.PNG)

However, opening jupyter notebook and choosing maxima as the kernel gives out a kernel error like this:

![KernelError](https://user-images.githubusercontent.com/63143891/108168849-e76e4880-7132-11eb-8d79-17a037c6a095.PNG)

The whole error log reads:
`Traceback (most recent call last):
  File "C:\Python39\lib\site-packages\tornado\web.py", line 1704, in _execute
    result = await result
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Python39\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 769, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Python39\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "C:\Python39\lib\site-packages\tornado\gen.py", line 762, in run
    value = future.result()
  File "C:\Python39\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "C:\Python39\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Python39\lib\site-packages\jupyter_client\manager.py", line 313, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "C:\Python39\lib\site-packages\jupyter_client\manager.py", line 222, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "C:\Python39\lib\site-packages\jupyter_client\launcher.py", line 134, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "C:\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified`

Is this an indication of a wrong path setting or is this an indication of an error somewhere in my installation process? Thank you!

**Comment by yitzchak** [comment]
If you are using Windows the installation is more difficult because of the cffi and static-vectors dependency in common-lisp-jupyter. I would go try to get common-lisp-jupyter working first. Also, I haven't used the old installation method for a very long time.
